#!/bin/bash
set -euo pipefail

# This script generates the cluster.yml configuration file with user inputs.
# It collects cluster parameters interactively or from environment variables and writes a YAML configuration
# that is consumed by deploy-cluster.sh.

# parameters (via environment variables, or prompted interactively)
# CLUSTER_NAME:        Name of the Kubernetes cluster
# MASTER_IP:           IP address of the master node
# MASTER_HOSTNAME:     Hostname of the master node
# WORKER_IPS:          Comma-separated list of worker node IP addresses
# WORKER_HOSTNAMES:    Comma-separated list of worker node hostnames
# POD_CIDR:            Pod network CIDR (default: 192.168.0.0/16)
# SERVICE_CIDR:        Service network CIDR (default: 10.96.0.0/12)
# KUBERNETES_VERSION:  Kubernetes version (default: 1.29)
# SSH_USER:            SSH user for all nodes
# SSH_KEY_PATH:        Path to SSH private key

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${CONFIG_FILE:-${SCRIPT_DIR}/cluster.yml}"

## 0. Validate IP address helper

validate_ip() {
    local ip="$1"
    if ! echo "$ip" | grep -qE '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'; then
        echo "ERROR: Invalid IP address format: $ip"
        return 1
    fi
}

## 1. Collect cluster parameters

echo "=== Kubernetes Cluster Configuration Generator ==="
echo ""

# Cluster name
if [ -z "${CLUSTER_NAME:-}" ]; then
    read -rp "Cluster name [my-cluster]: " CLUSTER_NAME
    CLUSTER_NAME="${CLUSTER_NAME:-my-cluster}"
fi

# SSH user
if [ -z "${SSH_USER:-}" ]; then
    read -rp "SSH user for all nodes [ubuntu]: " SSH_USER
    SSH_USER="${SSH_USER:-ubuntu}"
fi

# SSH key path
if [ -z "${SSH_KEY_PATH:-}" ]; then
    read -rp "SSH private key path [$HOME/.ssh/id_rsa_cluster]: " SSH_KEY_PATH
    SSH_KEY_PATH="${SSH_KEY_PATH:-$HOME/.ssh/id_rsa_cluster}"
fi

# Master node
if [ -z "${MASTER_IP:-}" ]; then
    read -rp "Master node IP address: " MASTER_IP
fi
validate_ip "$MASTER_IP"

if [ -z "${MASTER_HOSTNAME:-}" ]; then
    read -rp "Master node hostname [master-01]: " MASTER_HOSTNAME
    MASTER_HOSTNAME="${MASTER_HOSTNAME:-master-01}"
fi

# Worker nodes
if [ -z "${WORKER_IPS:-}" ]; then
    read -rp "Worker node IP addresses (comma-separated): " WORKER_IPS
fi

if [ -z "${WORKER_HOSTNAMES:-}" ]; then
    read -rp "Worker node hostnames (comma-separated) [auto-generated]: " WORKER_HOSTNAMES
fi

# Network settings
if [ -z "${POD_CIDR:-}" ]; then
    read -rp "Pod network CIDR [192.168.0.0/16]: " POD_CIDR
    POD_CIDR="${POD_CIDR:-192.168.0.0/16}"
fi

if [ -z "${SERVICE_CIDR:-}" ]; then
    read -rp "Service network CIDR [10.96.0.0/12]: " SERVICE_CIDR
    SERVICE_CIDR="${SERVICE_CIDR:-10.96.0.0/12}"
fi

# Kubernetes version
if [ -z "${KUBERNETES_VERSION:-}" ]; then
    read -rp "Kubernetes version [1.29]: " KUBERNETES_VERSION
    KUBERNETES_VERSION="${KUBERNETES_VERSION:-1.29}"
fi

## 2. Parse worker nodes into arrays

IFS=',' read -ra WORKER_IP_ARRAY <<< "$WORKER_IPS"
IFS=',' read -ra WORKER_HOSTNAME_ARRAY <<< "${WORKER_HOSTNAMES:-}"

# Auto-generate hostnames if not provided
if [ "${#WORKER_HOSTNAME_ARRAY[@]}" -eq 0 ] || [ -z "${WORKER_HOSTNAME_ARRAY[0]}" ]; then
    WORKER_HOSTNAME_ARRAY=()
    for i in "${!WORKER_IP_ARRAY[@]}"; do
        WORKER_HOSTNAME_ARRAY+=("worker-$(printf '%02d' $((i + 1)))")
    done
fi

# Validate worker count matches
if [ "${#WORKER_IP_ARRAY[@]}" -ne "${#WORKER_HOSTNAME_ARRAY[@]}" ]; then
    echo "ERROR: Number of worker IPs (${#WORKER_IP_ARRAY[@]}) does not match number of worker hostnames (${#WORKER_HOSTNAME_ARRAY[@]})."
    exit 1
fi

# Validate all worker IPs
for ip in "${WORKER_IP_ARRAY[@]}"; do
    ip="$(echo "$ip" | xargs)"  # trim whitespace
    validate_ip "$ip"
done

## 3. Generate cluster.yml

echo ""
echo "--- Generating cluster configuration: $CONFIG_FILE ---"

{
cat << YAML_EOF
# Kubernetes Cluster Configuration
# Generated by create-cluster-config.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
#
# This file is consumed by deploy-cluster.sh to orchestrate the cluster deployment.

# Cluster identification
cluster_name: ${CLUSTER_NAME}

# Kubernetes version (minor version, e.g. 1.29)
kubernetes_version: "${KUBERNETES_VERSION}"

# SSH configuration for remote node access
ssh:
  user: ${SSH_USER}
  key_path: ${SSH_KEY_PATH}

# Master node configuration
master:
  hostname: ${MASTER_HOSTNAME}
  ip: ${MASTER_IP}
  role: controlplane,etcd

# Worker node configuration
workers:
YAML_EOF

for i in "${!WORKER_IP_ARRAY[@]}"; do
    TRIMMED_IP="$(echo "${WORKER_IP_ARRAY[$i]}" | xargs)"
    TRIMMED_HOSTNAME="$(echo "${WORKER_HOSTNAME_ARRAY[$i]}" | xargs)"
    cat << YAML_WORKER
  - hostname: ${TRIMMED_HOSTNAME}
    ip: ${TRIMMED_IP}
    role: worker
YAML_WORKER
done

cat << YAML_NETWORK

# Network settings
network:
  # Pod network CIDR - used by the CNI plugin (Calico)
  pod_cidr: ${POD_CIDR}
  # Service network CIDR - used for ClusterIP services
  service_cidr: ${SERVICE_CIDR}
  # CNI plugin to install (calico is the default)
  cni_plugin: calico
YAML_NETWORK
} > "$CONFIG_FILE"

echo ""
echo "=== Cluster configuration generated successfully ==="
echo "Configuration file: $CONFIG_FILE"
echo ""
echo "Cluster summary:"
echo "  Name:               $CLUSTER_NAME"
echo "  Kubernetes version: $KUBERNETES_VERSION"
echo "  Master:             $MASTER_HOSTNAME ($MASTER_IP)"
echo "  Workers:            ${#WORKER_IP_ARRAY[@]} node(s)"
for i in "${!WORKER_IP_ARRAY[@]}"; do
    echo "                      ${WORKER_HOSTNAME_ARRAY[$i]} ($(echo "${WORKER_IP_ARRAY[$i]}" | xargs))"
done
echo "  Pod CIDR:           $POD_CIDR"
echo "  Service CIDR:       $SERVICE_CIDR"
